---
  MuranoEnvironments.create_and_deploy_environment:
    -
      args:
        packages_per_env: 1
        app_config: "/opt/stack/rally/rally-jobs/extra/murano/deployment_data/active_directory.json"
      runner:
        type: "constant"
        times: {{ (compute * 25 )//100 if not super_light else super_light_count }}
        concurrency: {{ (compute * 25 )//100 if not super_light else super_light_concurrency }}
      context:
        users:
          tenants: {{ (compute * 25 )//300 if not super_light else super_light_concurrency }}
          users_per_tenant: 1
        roles:
          - "admin"
