---
  MuranoEnvironments.list_environments:
    -
      runner:
        type: "constant"
        times: {{ compute * 20 if not super_light else super_light_count }}
        concurrency: {{ concurrency }}
      context:
        users:
          tenants: {{ compute * 2 }}
          users_per_tenant: 1
